remote_theme: pages-themes/minimal@v0.2.0
title: Yuhao Chen
logo: /assets/images/photo.jpg
description: Research Assistant Professor at the Vision and Image Processing Lab (VIP) at the University of Waterloo, yuhao.chen1 at uwaterloo.ca
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  is_project_page: false